{% set name = "revertex" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/revertex-{{ version }}.tar.gz
  sha256: ff09769451563809a98359d51e2b7de02fbb4e85443bdbae1c28453d9c9e7542

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - revertex = revertex.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - pyg4ometry
    - hist
    - scipy
    - numpy
    - awkward
    - legend-pydataobj >=1.11.6
    - legend-pygeom-hpges >=0.9.0
    - legend-pygeom-tools >=0.0.25
    - reboost
    - dbetto
    - matplotlib-base

test:
  imports:
    - revertex
  commands:
    - pip check
    - revertex -h
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Generate Geant4 event vertices in Python
  home: https://github.com/legend-exp/revertex
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://revertex.readthedocs.io
  dev_url: https://github.com/legend-exp/revertex

extra:
  recipe-maintainers:
    - gipert
    - ManuelHu
